defaults:
  - _self_
  - data

hydra:
  job:
    chdir: True

model:
  _target_: sklearn.linear_model.LogisticRegression
  C: 1.0
  max_iter: 1000
  random_state: 42
  solver: 'liblinear'
  verbose: 1